kind: pipeline
type: kubernetes
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: helm-lint
  image: alpine/helm
  commands:
  - helm lint helm/site
  - helm package helm/site

- name: build-image
  image: plugins/docker
  settings:
    mtu: 1440
    registry: registry.zanelab.com
    repo: registry.zanelab.com/zhala/site
    tags: 
      - ${DRONE_BUILD_NUMBER}
      - latest

- name: upload-helm-chart
  image: alpine
  environment:
    GITEA_PASSWORD:
      from_secret: gitea-password
  commands:
  - apk add curl
  - curl --user zhala:$GITEA_PASSWORD -X POST --upload-file ./site-*.tgz https://git.zanelab.com/api/packages/zhala/helm/api/charts
  when:
    branch: 
      - master
    event:
      - push