kind: pipeline
type: kubernetes
name: default

steps:
- name: helm-lint
  image: alpine/helm
  commands:
  - helm lint helm/site
- name: build-image
  image: plugins/docker
  settings:
    registry: registry.zanelab.com
    repo: registry.zanelab.com/zhala/site
    tags: 
      - ${DRONE_BUILD_NUMBER}
      - latest
- name: helm-deploy
  image: alpine/k8s
  environment:
    KUBECONFIGFILE:
      from_secret: kubeconfig
  commands:
  - echo $KUBECONFIGFILE > /tmp/kubeconfig.yaml
  - export KUBECONFIG=/tmp/kubeconfig.yaml
  - export BUILD_ID=${DRONE_BUILD_NUMBER}
  - helm upgrade site helm/site --set image.tag=$BUILD_ID --install --atomic --reuse-values 