kind: pipeline
type: kubernetes
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: helm-lint
  image: alpine/helm
  commands:
  - helm lint helm/site

- name: build-image
  image: plugins/docker
  settings:
    mtu: 1440
    registry: registry.zanelab.com
    repo: registry.zanelab.com/zhala/site
    tags: 
      - ${DRONE_BUILD_NUMBER}
      - latest
