kind: pipeline
type: kubernetes
name: default

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: helm-lint
  image: alpine/helm
  commands:
  - helm lint helm/site
  - helm package helm/site

- name: build-image
  image: plugins/docker
  settings:
    mtu: 1440
    registry: registry.zanelab.com
    repo: registry.zanelab.com/zhala/site
    tags: 
      - ${DRONE_BUILD_NUMBER}
      - latest

- name: test-image
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker run -d -p 80:80 registry.zanelab.com/zhala/site:${DRONE_BUILD_NUMBER}
  - apk add curl
  - curl --fail -LI 0.0.0.0:80 -o /dev/null -w '%{http_code}\n' -s > /dev/null
  - curl --fail -LI 0.0.0.0:80/test -o /dev/null -w '%{http_code}\n' -s > /dev/null

- name: upload-helm-chart
  image: alpine
  environment:
    GITEA_PASSWORD:
      from_secret: gitea-password
  commands:
  - apk add curl
  - curl --user zhala:$GITEA_PASSWORD -X POST --upload-file ./site-*.tgz https://git.zanelab.com/api/packages/zhala/helm/api/charts
  when:
    branch: 
      - master
    event:
      - push

- name: update-image-tag
  image: alpine
  environment:
    SSH_KEY:
      from_secret: git-ssh-key
  commands:
  - apk add git openssh-client
  - mkdir ~/.ssh
  - echo $SSH_KEY | base64 -d > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
  - ssh-keyscan git.zanelab.com >> ~/.ssh/known_hosts
  - ssh -vT -o StrictHostKeyChecking=no git@git.zanelab.com
  - git clone --depth=1 git@git.zanelab.com:zhala/homelab.git
  - | 
    cd homelab/apps/site && sed -i 's/tag: .*[0-9]/tag: ${DRONE_BUILD_NUMBER}/g' values.yaml
  - git config --global user.email "zmhala@gmail.com" && git config --global user.name "zhala"
  - git add . && git commit -m "Update site tag" && git push origin master
  when:
    branch: 
      - master
    event:
      - push
