baseURL = 'https://site.zanelab.com/'
languageCode = 'en-us'
title = "Zane's Lab"
theme = "PaperMod"
googleAnalytics = 'G-PTTW8P24PG'

[params]
defaultTheme = "auto"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "gravel map"
name = "Gravel Map"
url = "/gravel-map/"
weight = 10

[[menu.main]]
name = "github"
url = "https://github.com/zanehala"

[markup.goldmark.renderer]
 unsafe = true